# Generated by Django 3.1.4 on 2021-10-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20211025_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='categories',
            new_name='category',
        ),
    ]
